import test from 'node:test';
import assert from 'node:assert/strict';
import {SAVE_KEY,LEGACY_KEY,freshRecords,freshRecord,normalizeRecords,loadRecords,saveRecords} from '../src/save.js';
const memory=initial=>{const map=new Map(Object.entries(initial||{}));return {getItem:k=>map.has(k)?map.get(k):null,setItem:(k,v)=>map.set(k,v)};};
test('legacy clears migrate into diary one without altering the legacy backup',()=>{const old=JSON.stringify({0:true,2:true,8:true,1:'yes'}),storage=memory({[LEGACY_KEY]:old});const {data}=loadRecords(storage);assert.deepEqual(data.slots[0].cleared,[0,2]);assert.deepEqual(data.slots.slice(1),[null,null]);assert.equal(saveRecords(data,storage),true);assert.equal(storage.getItem(LEGACY_KEY),old);assert.deepEqual(loadRecords(storage).data.slots[0].cleared,[0,2]);});
test('three diaries retain independent clears and introduction state through reload',()=>{const storage=memory(),data=freshRecords();data.slots[0]={...freshRecord(),cleared:[0],introSeen:true};data.slots[1]={...freshRecord(),cleared:[2]};data.slots[2]=freshRecord();data.active=1;assert.ok(saveRecords(data,storage));const next=loadRecords(storage).data;assert.deepEqual(next.slots.map(s=>s.cleared),[[0],[2],[]]);assert.deepEqual(next.slots.map(s=>s.introSeen),[true,false,false]);assert.equal(next.active,1);});
test('deleting a migrated diary never resurrects legacy progress or changes other diaries',()=>{const storage=memory({[LEGACY_KEY]:'{"0":true}'}),data=loadRecords(storage).data;data.slots[1]={...freshRecord(),cleared:[3]};saveRecords(data,storage);data.slots[0]=null;assert.ok(saveRecords(data,storage));assert.equal(loadRecords(storage).data.slots[0],null);assert.deepEqual(loadRecords(storage).data.slots[1].cleared,[3]);});
test('stale tabs cannot overwrite newer saved records',()=>{const storage=memory(),a=loadRecords(storage).data,b=loadRecords(storage).data;a.slots[0]=freshRecord();assert.ok(saveRecords(a,storage));b.slots[1]=freshRecord();assert.equal(saveRecords(b,storage),false);assert.equal(loadRecords(storage).data.slots[1],null);});
test('corrupt and future records are not overwritten, unavailable storage is reported',()=>{for(const raw of ['broken','{"version":99,"slots":[]}']){const storage=memory({[SAVE_KEY]:raw});assert.ok(loadRecords(storage).error);assert.equal(saveRecords(freshRecords(),storage),false);assert.equal(storage.getItem(SAVE_KEY),raw);}assert.ok(loadRecords(null).error);assert.equal(saveRecords(freshRecords(),{getItem:()=>null,setItem:()=>{throw new Error('quota');}}),false);});
test('normalization bounds clear IDs and slot count',()=>{const data=normalizeRecords({version:2,active:8,slots:[{cleared:[0,0,5,6,-1,'2'],introSeen:1},null,null,{}]});assert.equal(data.slots.length,3);assert.deepEqual(data.slots[0].cleared,[0,5]);assert.equal(data.slots[0].introSeen,false);assert.equal(data.active,0);});

test('v2 chapter clears migrate to completed stages without inventing star ratings',()=>{const raw={version:2,revision:4,active:0,slots:[{cleared:[0,5],introSeen:true},null,null]};const storage=memory({[SAVE_KEY]:JSON.stringify(raw)}),r=loadRecords(storage).data;assert.deepEqual(r.slots[0].stages,[0,1,2,3,4,5,30,31,32,33,34,35]);assert.deepEqual(r.slots[0].stars,{});assert.ok(saveRecords(r,storage));assert.deepEqual(loadRecords(storage).data.slots[0].stages,r.slots[0].stages);});
test('stars and endless records stay isolated across save slots and reload',()=>{const storage=memory(),r=freshRecords();r.slots[0]={...freshRecord(),stages:[0],stars:{0:{stars:3,time:15,mistakes:0}},endless:{best:28,total:50}};r.slots[1]=freshRecord();assert.ok(saveRecords(r,storage));const s=loadRecords(storage).data.slots;assert.equal(s[0].stars[0].stars,3);assert.equal(s[0].endless.best,28);assert.deepEqual(s[1].stars,{});assert.equal(s[1].endless.best,0);});
test('shop emblems migrate safely and remain independent in all three diaries',()=>{const storage=memory(),r=freshRecords();r.slots=[0,1,2].map(shopEmblem=>({...freshRecord(),shopEmblem}));assert.ok(saveRecords(r,storage));assert.deepEqual(loadRecords(storage).data.slots.map(s=>s.shopEmblem),[0,1,2]);for(const invalid of [undefined,-1,3,'2',{},null]){const data=normalizeRecords({version:2,slots:[{cleared:[],shopEmblem:invalid},null,null]});assert.equal(data.slots[0].shopEmblem,0);}});
