import {mod, normalizeTime, clockAngles, angleDelta, dragMinutes, matchesTime, timeText, orderHint} from './time.js';
import {levels, makeOrder, createSession, tickSession, completeOrder} from './levels.js';

const app=document.querySelector('#app');
const $=selector=>app.querySelector(selector);
let screen='home', session=null, dial=720, selectedHand='hour', paused=false, busy=false, drag=null, timer=null, flightTimer=null;
let lastTick=0, soundOn=false, audio=null, introIndex=0;
let progress={};
try{const value=JSON.parse(localStorage.getItem('miracle-clock.progress.v1')||'{}');if(value&&typeof value==='object'&&!Array.isArray(value))progress=value;}catch{}
const portrait=(id,cls='')=>`<span class="portrait cast-${id} ${cls}" role="img" aria-label="${['ルカ','モス','シェル','クリム','フレア','フウ'][id]}"></span>`;
const toto=(cls='')=>`<img class="toto ${cls}" src="assets/sky-toto.webp" alt="トトじい">`;
const smallClock=(time)=>{const a=clockAngles(time);return `<svg viewBox="0 0 60 60" class="mini-clock" aria-label="${timeText(time,'period')}"><circle cx="30" cy="30" r="27"/><path d="M30 30V15" transform="rotate(${a.hour} 30 30)"/><path d="M30 30V8" transform="rotate(${a.minute} 30 30)" class="mini-minute"/><circle cx="30" cy="30" r="2"/></svg>`;};
function playSound(kind){
  if(!soundOn)return;
  try{audio ||= new (window.AudioContext||window.webkitAudioContext)();audio.resume();const notes=kind==='win'?[523,659,784,1047]:kind==='send'?[440,659,880]:kind==='wrong'?[294,262]:[660];notes.forEach((f,i)=>{const o=audio.createOscillator(),g=audio.createGain(),t=audio.currentTime+i*.12;o.type='sine';o.frequency.value=f;g.gain.setValueAtTime(0,t);g.gain.linearRampToValueAtTime(.08,t+.015);g.gain.exponentialRampToValueAtTime(.001,t+.22);o.connect(g);g.connect(audio.destination);o.start(t);o.stop(t+.25);});}catch{}
}
function cleanup(){clearInterval(timer);clearTimeout(flightTimer);timer=null;drag=null;busy=false;paused=false;document.body.classList.remove('flying');}
function renderHome(){
  cleanup();screen='home';
  app.innerHTML=`<main class="home scene"><div class="vignette"></div><header class="home-header"><span class="edition">MIRACLE MINE の、その先へ</span><button class="icon-button sound" aria-pressed="${soundOn}">音 ${soundOn?'ON':'OFF'}</button></header><div class="title-lockup"><p class="eyebrow">A LITTLE TIME. A BIG ADVENTURE.</p><h1><span>Miracle</span><span>Clock</span></h1><p class="subtitle">ルカと空のとけい便</p><span class="title-rule"></span><p class="home-copy">きみが合わせた時刻に、<br>だれかの「ありがとう」が届く。</p></div><img class="home-plane" src="assets/delivery-plane.webp" alt="荷物を積んだ蒸気飛行機"><div class="home-cast">${portrait(0,'home-luka')}${toto('home-toto')}</div><div class="home-actions"><button class="primary" id="start">空の配送屋さんへ <span>→</span></button><button class="text-button" id="story">はじまりの物語</button><small>時計の針を動かして、荷物を届けよう。</small></div><footer class="home-footer">MIRACLE CLOCK <span>はじめての配達版 · v0.1</span></footer></main>`;
  $('#start').onclick=renderMap;$('#story').onclick=()=>showStory();bindSound();
}
function bindSound(){ $('.sound')?.addEventListener('click',e=>{soundOn=!soundOn;e.currentTarget.textContent=`音 ${soundOn?'ON':'OFF'}`;e.currentTarget.setAttribute('aria-pressed',soundOn);if(soundOn)playSound('tap');});}
function showStory(){
 const stories=[['ルカ','飛行機、こんなにたくさんできたね！ これなら、島のみんなの荷物を運べるよ。'],['トトじい','これは「とけいの羅針盤」。届けたい時刻を合わせると、飛行機が自分で空の道を選んでくれるんじゃ。'],['ルカ','森にも、港にも、雲の向こうにも。よし、「空のとけい便」開店だ！']];
 introIndex=0;
 function frame(){const [name,text]=stories[introIndex];openModal(`<div class="story-portrait">${name==='ルカ'?portrait(0):toto()}</div><p class="eyebrow">はじまりの物語</p><h2>${name}</h2><p>${text}</p><button class="primary" id="story-next">${introIndex===stories.length-1?'配送屋さんへ':'つぎへ'} →</button>`);$('#story-next').onclick=()=>{introIndex++;if(introIndex<stories.length)frame();else{closeModal();renderMap();}};}
 frame();
}
function renderMap(){
 cleanup();screen='map';
 app.innerHTML=`<main class="map scene"><header class="topbar"><button class="subtle" id="home">← タイトル</button><span class="wordmark">Miracle Clock</span><button class="icon-button sound" aria-pressed="${soundOn}">音 ${soundOn?'ON':'OFF'}</button></header><section class="map-heading"><p class="eyebrow">LUCA & TOTO'S AIR POST</p><h1>今日は、どの島へ？</h1><p>好きな島から、何度でも。ゆっくり練習もできるよ。</p></section><div class="level-grid">${levels.map(l=>`<button class="level-card" data-level="${l.id}"><div class="level-art">${portrait(l.id%5+1)}<span class="chapter-number">0${l.id+1}</span>${progress[l.id]?' <span class="stamp">配達ずみ</span>':''}</div><div class="level-details"><span class="eyebrow">${l.place}</span><h2>${l.title}</h2><p>${l.skill}</p><span class="level-go">この島へ →</span></div></button>`).join('')}</div><p class="save-note">配達の記録は、この端末に自動で保存されます。</p></main>`;
 $('#home').onclick=renderHome;bindSound();document.querySelectorAll('[data-level]').forEach(b=>b.onclick=()=>chooseLevel(levels[Number(b.dataset.level)]));
}
function chooseLevel(level){openModal(`<div class="modal-companion">${toto()}</div><p class="eyebrow">第${level.id+1}章 · ${level.place}</p><h2>${level.title}</h2><p>${level.intro}</p><div class="lesson">${level.lesson}</div><button class="primary" id="practice">トトじいと練習 <small>行列なし・3件</small></button><button class="secondary" id="open-shop">お店をひらく <small>${level.count}件お届け・行列あり</small></button>`);$('#practice').onclick=()=>{closeModal();startLevel(level,true);};$('#open-shop').onclick=()=>{closeModal();startLevel(level,false);};}
function openModal(content,closable=true){closeModal();const wrapper=document.createElement('div');wrapper.className='modal-backdrop';wrapper.innerHTML=`<section class="modal" role="dialog" aria-modal="true" aria-label="${screen==='play'?'配達のお知らせ':'お知らせ'}">${closable?'<button class="modal-close" aria-label="閉じる">×</button>':''}${content}</section>`;app.append(wrapper);$('.modal-close')?.addEventListener('click',()=>{closeModal();if(screen==='play'){paused=false;lastTick=performance.now();}});wrapper.querySelector('button')?.focus();wrapper.addEventListener('keydown',e=>{if(e.key==='Escape'&&closable){e.preventDefault();$('.modal-close')?.click();}if(e.key==='Tab'){const items=[...wrapper.querySelectorAll('button:not(:disabled)')];const first=items[0],last=items.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus();}}});}
function closeModal(){$('.modal-backdrop')?.remove();}
function clockMarkup(){
 let ticks='',numbers='',minutes='';
 for(let i=0;i<60;i++){const rad=i*Math.PI/30;const outer=137,inner=i%5===0?125:132;ticks+=`<line x1="${150+inner*Math.sin(rad)}" y1="${150-inner*Math.cos(rad)}" x2="${150+outer*Math.sin(rad)}" y2="${150-outer*Math.cos(rad)}" class="tick ${i%5===0?'major':''}"/>`;}
 for(let i=1;i<=12;i++){const rad=i*Math.PI/6;numbers+=`<text x="${150+108*Math.sin(rad)}" y="${150-108*Math.cos(rad)}" class="hour-number">${i}</text>`;minutes+=`<text x="${150+80*Math.sin(rad)}" y="${150-80*Math.cos(rad)}" class="minute-number">${i===12?'00':i*5}</text>`;}
 return `<svg id="clock" viewBox="0 0 300 300" aria-label="お届け時刻を合わせる時計"><circle class="clock-face" cx="150" cy="150" r="146"/><circle class="dial-ring" cx="150" cy="150" r="141"/>${ticks}${numbers}<g class="minute-guide">${minutes}</g><text x="150" y="207" class="dial-brand">MIRACLE</text><text x="150" y="220" class="dial-caption">AIR POST</text><g id="hour-hand" data-hand="hour" role="slider" tabindex="0" aria-label="短い針・時" aria-valuemin="1" aria-valuemax="12"><line class="hand-hit" x1="150" y1="159" x2="150" y2="73"/><path class="hour-hand" d="M144 160L143 94L150 71L157 94L156 160Z"/><circle cx="150" cy="87" r="3" fill="#f9dfa0"/></g><g id="minute-hand" data-hand="minute" role="slider" tabindex="0" aria-label="長い針・分" aria-valuemin="0" aria-valuemax="59"><line class="hand-hit" x1="150" y1="160" x2="150" y2="34"/><path class="minute-hand" d="M147 164L146 57L150 34L154 57L153 164Z"/></g><circle class="pivot-outer" cx="150" cy="150" r="11"/><circle class="pivot" cx="150" cy="150" r="5"/></svg>`;
}
function startLevel(level,practice){
 cleanup();screen='play';session=createSession(level,practice);selectedHand=level.id===0?'hour':'minute';dial=level.id===5?session.queue[0].base:720;
 app.innerHTML=`<main class="game scene"><header class="topbar game-top"><button class="subtle" id="pause" aria-label="一時停止">Ⅱ おやすみ</button><div class="stage-heading"><span class="eyebrow">${practice?'トトじいと練習':`第${level.id+1}章 · ${level.place}`}</span><strong>${level.title}</strong></div><span id="score" class="score"></span></header><section class="queue-area" aria-label="待っているお客さん"><div class="queue-heading"><span>${practice?'ゆっくりで大丈夫':'お客さんの行列'}</span><span id="queue-count"></span></div><div class="queue-track" id="queue"></div><div class="arrival-track" ${practice?'hidden':''}><span id="arrival-fill"></span></div></section><div class="play-layout"><aside class="companion-side"><div class="luka-frame">${portrait(0)}<span class="magic-ring"></span></div><div class="luka-note"><b>ルカの とけいの羅針盤</b><p>針を合わせたら、<br>空の道へ出発！</p></div><div class="plane-dock"><img src="assets/delivery-plane.webp" alt="出発を待つ配送飛行機"></div></aside><section class="clock-station"><div class="order-ticket" id="order"></div><div class="clock-housing"><div class="clock-crown"></div>${clockMarkup()}<div class="clock-status" id="clock-status">お届け時刻を合わせよう</div></div><div class="station-controls"><div class="period-toggle" id="period-toggle" hidden><button data-period="0">☀ 午前</button><button data-period="1">☾ 午後</button></div><div class="hand-controls"><button class="hand-select" data-select="hour"><i class="short-swatch"></i>短い針</button><button class="adjust" id="minus" aria-label="選んだ針を戻す">−</button><button class="adjust" id="plus" aria-label="選んだ針を進める">＋</button><button class="hand-select" data-select="minute"><i class="long-swatch"></i>長い針</button></div><button class="primary dispatch" id="dispatch">この時刻に届ける <span>→</span></button><div class="clock-tools"><button class="text-button" id="guide" aria-pressed="${practice}">分のめもり ${practice?'ON':'OFF'}</button><button class="text-button" id="hint">トトじいのヒント</button></div></div></section><aside class="toto-side"><div class="toto-advice">${toto()}<div><b>トトじい</b><p id="advice">${level.lesson}</p></div></div><div class="delivery-log"><span class="eyebrow">TODAY'S FLIGHTS</span><h2>今日のお届け</h2><ol id="flight-log"><li>最初の便を待っています</li></ol></div></aside></div><div class="flight-layer" aria-hidden="true"><div class="magic-flash"></div><img src="assets/delivery-plane.webp" alt=""></div><div class="feedback" id="feedback" role="status" aria-live="polite"></div></main>`;
 $('#clock').classList.toggle('show-guide',practice);$('#pause').onclick=()=>pauseGame();$('#dispatch').onclick=dispatch;
 document.querySelectorAll('[data-select]').forEach(b=>b.onclick=()=>{selectedHand=b.dataset.select;updateDial();});
 $('#minus').onclick=()=>adjust(-1);$('#plus').onclick=()=>adjust(1);
 document.querySelectorAll('[data-period]').forEach(b=>b.onclick=()=>{if(busy||paused)return;dial=mod(dial,720)+Number(b.dataset.period)*720;updateDial();});
 $('#guide').onclick=e=>{const on=$('#clock').classList.toggle('show-guide');e.currentTarget.textContent=`分のめもり ${on?'ON':'OFF'}`;e.currentTarget.setAttribute('aria-pressed',on);};
 $('#hint').onclick=()=>{if(busy||paused)return;$('#advice').textContent=orderHint(session.queue[0],dial);$('#feedback').textContent=orderHint(session.queue[0],dial);};
 bindDial();updateOrder();updateQueue();updateDial();lastTick=performance.now();timer=setInterval(tick,100);
}
function updateOrder(){const order=session.queue[0];if(!order)return;$('#order').innerHTML=`<div class="ticket-meta"><span>${order.name}からの おねがい</span><span>${order.parcel}</span></div><p class="request"><strong>${order.label}</strong><span>に届けてね！</span></p>${order.duration?`<div class="reference-time">${smallClock(order.base)}<span>受付の時刻 <b>${timeText(order.base,'period')}</b></span>${order.nextDay?'<span class="tomorrow">翌日のお届け</span>':''}</div>`:''}`;if(order.duration)$('#order .request span').textContent='に届くように！';$('#period-toggle').hidden=!order.period;$('#score').textContent=`${session.delivered} / ${session.practice?3:session.level.count} 便`;$('.clock-status').textContent=order.step===1?'小さな1目盛りは、1分':'お届け時刻を合わせよう';}
function updateQueue(){const q=session.queue;$('#queue-count').textContent=session.practice?'練習中':`${q.length} / ${session.capacity} 人`;$('#queue').innerHTML=q.map((o,i)=>`<div class="customer ${i===0?'active':''}"><div class="customer-bubble">${o.label}</div>${portrait(o.characterId)}<span>${o.name}</span></div>`).join('');$('#queue').classList.toggle('crowded',q.length>=4);}
function updateDial(){const angles=clockAngles(dial);$('#hour-hand').setAttribute('transform',`rotate(${angles.hour} 150 150)`);$('#minute-hand').setAttribute('transform',`rotate(${angles.minute} 150 150)`);$('#hour-hand').setAttribute('aria-valuenow',Math.floor(mod(dial,720)/60)||12);$('#minute-hand').setAttribute('aria-valuenow',mod(dial,60));$('#hour-hand').setAttribute('aria-valuetext',timeText(dial));$('#minute-hand').setAttribute('aria-valuetext',`${mod(dial,60)}分`);document.querySelectorAll('[data-select]').forEach(b=>b.setAttribute('aria-pressed',b.dataset.select===selectedHand));document.querySelectorAll('[data-period]').forEach(b=>b.setAttribute('aria-pressed',Number(b.dataset.period)===Math.floor(dial/720)));}
function adjust(direction){if(paused||busy)return;dial=normalizeTime(dial+direction*(selectedHand==='hour'?60:session.queue[0].step));updateDial();playSound('tap');}
function bindDial(){const clock=$('#clock');const angle=e=>{const b=clock.getBoundingClientRect();return mod(Math.atan2(e.clientX-b.left-b.width/2,-(e.clientY-b.top-b.height/2))*180/Math.PI,360);};
 clock.addEventListener('pointerdown',e=>{if(paused||busy||drag)return;e.preventDefault();let hand=e.target.closest('[data-hand]')?.dataset.hand||selectedHand;const bounds=clock.getBoundingClientRect(),radius=Math.hypot(e.clientX-bounds.left-bounds.width/2,e.clientY-bounds.top-bounds.height/2)*300/bounds.width;const a=clockAngles(dial);if(selectedHand==='hour'&&radius<95&&Math.abs(angleDelta(a.hour,a.minute))<14)hand='hour';selectedHand=hand;drag={pointer:e.pointerId,hand,start:dial,last:angle(e),delta:0};clock.setPointerCapture(e.pointerId);clock.classList.add('dragging');updateDial();});
 clock.addEventListener('pointermove',e=>{if(!drag||e.pointerId!==drag.pointer||busy||paused)return;e.preventDefault();const next=angle(e);drag.delta+=angleDelta(drag.last,next);drag.last=next;dial=dragMinutes(drag.start,drag.delta,drag.hand,session.queue[0].step);updateDial();});
 const end=e=>{if(!drag||e.pointerId!==drag.pointer)return;drag=null;clock.classList.remove('dragging');};clock.addEventListener('pointerup',end);clock.addEventListener('pointercancel',end);clock.addEventListener('lostpointercapture',end);
 document.querySelectorAll('[data-hand]').forEach(h=>h.addEventListener('keydown',e=>{if(['ArrowLeft','ArrowDown','ArrowRight','ArrowUp'].includes(e.key)){e.preventDefault();selectedHand=h.dataset.hand;adjust(['ArrowLeft','ArrowDown'].includes(e.key)?-1:1);}}));
}
function tick(){const now=performance.now(),seconds=(now-lastTick)/1000;lastTick=now;if(paused||busy||document.hidden||session.status!=='playing')return;const before=session.queue.length;tickSession(session,seconds);if(before!==session.queue.length)updateQueue();$('#arrival-fill').style.width=`${session.generated>=session.level.count?0:session.elapsed/session.level.interval*100}%`;if(session.status==='over')finish(false);}
function dispatch(){
 if(paused||busy||session.status!=='playing')return;const order=session.queue[0];drag=null;
 if(!matchesTime(dial,order.target,order.period)){session.mistakes++;playSound('wrong');$('#feedback').textContent=`いまの針は${timeText(dial,order.period?'period':'12')}。${orderHint(order,dial)}`;$('.clock-housing').classList.remove('shake');void $('.clock-housing').offsetWidth;$('.clock-housing').classList.add('shake');return;}
 busy=true;$('#dispatch').disabled=true;playSound('send');document.body.classList.add('flying');$('#feedback').textContent=`ぴったり！ ${order.destination}へ、出発！`;
 const log=$('#flight-log');if(!session.delivered)log.innerHTML='';const li=document.createElement('li');li.innerHTML=`<span>✓ ${order.name}</span><b>${timeText(order.target,order.period?'period':'12')}</b>`;log.prepend(li);if(log.children.length>5)log.lastChild.remove();
 flightTimer=setTimeout(()=>{document.body.classList.remove('flying');completeOrder(session);busy=false;if(session.status==='cleared'){finish(true);return;}$('#dispatch').disabled=false;$('#feedback').textContent='';if(session.level.id===5)dial=session.queue[0].base;updateOrder();updateQueue();updateDial();},1100);
}
function pauseGame(){if(busy||session.status!=='playing')return;paused=true;drag=null;openModal(`<p class="eyebrow">ひとやすみ</p><h2>空の便も、おやすみ中。</h2><p>時計も、お客さんの行列も止まっています。</p><button class="primary" id="resume">つづける</button><button class="secondary" id="quit">島えらびにもどる</button><button class="text-button sound" aria-pressed="${soundOn}">音 ${soundOn?'ON':'OFF'}</button>`,false);$('#resume').onclick=()=>{closeModal();paused=false;lastTick=performance.now();};$('#quit').onclick=renderMap;bindSound();}
function finish(won){clearInterval(timer);timer=null;const practice=session.practice;playSound(won?'win':'wrong');
 if(won&&!practice){progress[session.level.id]=true;try{localStorage.setItem('miracle-clock.progress.v1',JSON.stringify(progress));}catch{}}
 openModal(`<div class="result-character">${won?portrait(0):toto()}</div><p class="eyebrow">${won?(practice?'PRACTICE COMPLETE':'DELIVERY COMPLETE'):'TAKE A LITTLE BREAK'}</p><h2>${won?(practice?'時計と、なかよくなれたね！':'みんなの荷物が届いたよ！'):'今日は、ここでひとやすみ。'}</h2><p>${won?(practice?'こんどは、お店をひらいてみよう。':`${session.delivered}件の「ありがとう」が、空を渡りました。`):'行列がいっぱいになっちゃった。練習でゆっくり針を動かして、また挑戦しよう。'}</p><button class="primary" id="result-main">${practice&&won?'お店をひらく':won&&session.level.id<5?'次の島へ':'もう一度あそぶ'}</button><button class="secondary" id="result-map">島えらびにもどる</button>${!won?'<button class="text-button" id="result-practice">トトじいと練習する</button>':''}`,false);
 $('#result-main').onclick=()=>{const l=session.level;if(practice&&won)startLevel(l,false);else if(won&&l.id<5) {renderMap();chooseLevel(levels[l.id+1]);}else startLevel(l,practice);};$('#result-map').onclick=renderMap;$('#result-practice')?.addEventListener('click',()=>startLevel(session.level,true));
}
document.addEventListener('visibilitychange',()=>{lastTick=performance.now();if(document.hidden&&screen==='play'&&!paused&&!busy&&session?.status==='playing')pauseGame();});
renderHome();
